// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package sql

import __yyfmt__ "fmt"

//line parser.go.y:2

//line parser.go.y:5
type yySymType struct {
	yys                  int
	literal              string
	identifier           string
	signedNumber         int64
	statement            interface{}
	columnNameList       []string
	columnName           string
	columnDefList        []ColumnDef
	columnDef            ColumnDef
	indexedColumnList    []IndexedColumn
	indexedColumn        IndexedColumn
	name                 string
	withoutRowid         bool
	unique               bool
	bool                 bool
	collate              string
	sortOrder            SortOrder
	columnConstraint     columnConstraint
	columnConstraintList []columnConstraint
	tableConstraint      TableConstraint
	tableConstraintList  []TableConstraint
	foreignKeyClause     ForeignKeyClause
	triggerAction        TriggerAction
	trigger              Trigger
	triggerList          []Trigger
	where                Expression
	expr                 Expression
	exprList             []Expression
	float                float64
}

const ABORT = 57346
const ACTION = 57347
const AND = 57348
const ASC = 57349
const AUTOINCREMENT = 57350
const CASCADE = 57351
const COLLATE = 57352
const CONFLICT = 57353
const CONSTRAINT = 57354
const CREATE = 57355
const DEFAULT = 57356
const DEFERRABLE = 57357
const DEFERRED = 57358
const DELETE = 57359
const DESC = 57360
const FAIL = 57361
const FOREIGN = 57362
const FROM = 57363
const GLOB = 57364
const IGNORE = 57365
const IN = 57366
const INDEX = 57367
const INITIALLY = 57368
const IS = 57369
const KEY = 57370
const LIKE = 57371
const MATCH = 57372
const NO = 57373
const NOT = 57374
const NULL = 57375
const ON = 57376
const OR = 57377
const PRIMARY = 57378
const REFERENCES = 57379
const REGEXP = 57380
const REPLACE = 57381
const RESTRICT = 57382
const ROLLBACK = 57383
const ROWID = 57384
const SELECT = 57385
const SET = 57386
const TABLE = 57387
const UNIQUE = 57388
const UPDATE = 57389
const WHERE = 57390
const WITHOUT = 57391
const tBare = 57392
const tLiteral = 57393
const tIdentifier = 57394
const tOperator = 57395
const tSignedNumber = 57396
const tFloat = 57397

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ABORT",
	"ACTION",
	"AND",
	"ASC",
	"AUTOINCREMENT",
	"CASCADE",
	"COLLATE",
	"CONFLICT",
	"CONSTRAINT",
	"CREATE",
	"DEFAULT",
	"DEFERRABLE",
	"DEFERRED",
	"DELETE",
	"DESC",
	"FAIL",
	"FOREIGN",
	"FROM",
	"GLOB",
	"IGNORE",
	"IN",
	"INDEX",
	"INITIALLY",
	"IS",
	"KEY",
	"LIKE",
	"MATCH",
	"NO",
	"NOT",
	"NULL",
	"ON",
	"OR",
	"PRIMARY",
	"REFERENCES",
	"REGEXP",
	"REPLACE",
	"RESTRICT",
	"ROLLBACK",
	"ROWID",
	"SELECT",
	"SET",
	"TABLE",
	"UNIQUE",
	"UPDATE",
	"WHERE",
	"WITHOUT",
	"tBare",
	"tLiteral",
	"tIdentifier",
	"tOperator",
	"tSignedNumber",
	"tFloat",
	"'-'",
	"'+'",
	"','",
	"'('",
	"')'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 85,
	59, 6,
	-2, 92,
	-1, 86,
	59, 7,
	-2, 93,
}

const yyPrivate = 57344

const yyLast = 214

var yyAct = [...]int{

	167, 81, 79, 49, 9, 123, 82, 10, 76, 66,
	77, 96, 144, 83, 109, 54, 19, 111, 110, 10,
	22, 136, 24, 109, 67, 10, 111, 110, 27, 33,
	33, 35, 10, 118, 142, 27, 151, 105, 80, 148,
	58, 71, 72, 116, 147, 68, 146, 69, 70, 112,
	73, 142, 74, 143, 65, 85, 84, 86, 75, 68,
	90, 88, 89, 102, 87, 105, 105, 138, 106, 104,
	39, 103, 40, 92, 53, 94, 99, 100, 68, 90,
	88, 89, 68, 30, 69, 70, 51, 61, 23, 18,
	113, 12, 165, 13, 128, 99, 100, 95, 11, 42,
	38, 117, 114, 115, 10, 159, 12, 124, 13, 71,
	72, 125, 131, 132, 133, 135, 126, 36, 130, 129,
	10, 6, 166, 124, 139, 137, 17, 28, 14, 16,
	11, 145, 28, 57, 50, 11, 150, 41, 12, 169,
	13, 62, 48, 12, 10, 13, 47, 154, 29, 55,
	155, 5, 62, 64, 174, 157, 161, 59, 26, 56,
	20, 171, 93, 32, 45, 44, 91, 172, 43, 50,
	170, 162, 52, 173, 168, 163, 63, 141, 46, 97,
	8, 153, 122, 38, 156, 108, 120, 175, 149, 37,
	98, 164, 34, 160, 140, 121, 134, 78, 21, 127,
	152, 158, 31, 119, 107, 60, 15, 25, 7, 101,
	4, 3, 2, 1,
}
var yyPact = [...]int{

	108, -1000, -1000, -1000, -1000, 56, 83, 68, -1000, -1000,
	-1000, -1000, -1000, -1000, 41, 135, -1000, 56, 41, 29,
	41, -1000, -1000, 93, 114, 25, -1000, 41, 41, 41,
	88, 12, 132, 27, 132, 15, 113, -1000, 41, 171,
	38, 132, -1000, 148, -1000, 120, -1000, -9, 41, -1000,
	41, 28, 132, 5, -1000, 138, 14, 134, -1000, 113,
	-1000, 55, -1000, 172, -1000, -1000, -1000, -1000, -1000, 28,
	28, -1000, -1000, -1000, 4, 11, 8, -1000, 175, -30,
	-1000, -10, -1000, -1000, -1000, -1000, -1000, 5, 24, 24,
	-1000, -16, 5, -26, -1000, -1000, 178, -1000, -1000, -1000,
	-1000, 167, 56, -1000, 28, 5, 46, 172, 59, 5,
	5, 5, 5, -39, -1000, -1000, 5, 7, 56, -1000,
	-1000, 151, -1000, -7, -1000, -48, -1000, -1000, 5, -1000,
	-1000, -30, -30, -30, -14, -30, -1000, -21, 102, -24,
	-1000, 165, 56, -1000, -1000, -30, -1000, 5, -1000, -1000,
	173, 97, 71, -1000, -1000, -30, 152, -1000, -1000, 75,
	-1000, -1000, -1000, -1000, -1000, 130, 130, -1000, 140, -1000,
	-1000, 182, -1000, -1000, -1000, -1000,
}
var yyPgo = [...]int{

	0, 213, 212, 211, 210, 1, 9, 6, 13, 4,
	180, 5, 209, 208, 207, 158, 8, 10, 163, 117,
	206, 205, 204, 11, 203, 99, 137, 15, 202, 3,
	0, 201, 200, 199, 197, 2, 196, 195, 194, 188,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 6, 6, 5, 5, 7, 7,
	7, 8, 8, 8, 9, 9, 11, 11, 12, 10,
	13, 13, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 26, 26, 26, 27, 27, 27, 29, 19, 19,
	28, 28, 28, 24, 24, 14, 14, 15, 15, 18,
	18, 18, 18, 22, 22, 23, 23, 23, 21, 21,
	20, 20, 39, 39, 39, 39, 39, 39, 16, 16,
	34, 17, 30, 30, 30, 30, 30, 31, 31, 32,
	32, 37, 37, 38, 38, 33, 33, 35, 35, 35,
	35, 35, 35, 35, 35, 35, 35, 35, 36, 36,
	36, 2, 3, 4,
}
var yyR2 = [...]int{

	0, 1, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 1, 2, 2, 1, 1, 1, 3, 3, 1,
	1, 3, 4, 1, 2, 1, 2, 2, 2, 2,
	1, 0, 1, 2, 5, 5, 6, 6, 0, 2,
	0, 3, 4, 0, 1, 1, 3, 3, 3, 0,
	1, 4, 6, 0, 2, 0, 1, 1, 0, 2,
	0, 1, 0, 3, 3, 3, 3, 3, 1, 3,
	1, 3, 2, 2, 1, 1, 2, 3, 3, 0,
	2, 0, 1, 0, 2, 0, 2, 1, 4, 1,
	1, 1, 1, 1, 3, 3, 3, 3, 0, 1,
	3, 4, 8, 10,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, -4, 43, 13, -13, -10, -9,
	-5, 42, 50, 52, 45, -20, 46, 58, 21, -5,
	25, -10, -5, 59, -5, -14, -15, -9, 39, 34,
	58, -28, -18, -5, -18, -5, -19, -15, 12, 58,
	60, -26, -25, 36, 33, 32, 46, 14, 10, -29,
	37, 59, -26, 59, -27, 36, 46, 20, -5, -19,
	-21, 49, -25, 28, 33, -7, -6, 33, 54, 56,
	57, 50, 51, -5, -5, -7, -16, -17, -34, -35,
	33, -5, -7, -8, 51, 50, 52, 59, 56, 57,
	55, 28, 59, 28, -27, 42, -23, 7, 18, -7,
	-7, -12, 59, 60, 58, 58, 60, -22, 10, 53,
	57, 56, 59, -35, -8, -8, 59, -16, 59, -24,
	8, -37, 15, -11, -9, -7, -17, -33, 48, -23,
	-6, -35, -35, -35, -36, -35, 60, -16, 60, -11,
	-38, 26, 58, 60, 60, -35, 60, 58, 60, -39,
	34, 60, -32, 16, -9, -35, 11, -29, -31, 34,
	41, 4, 19, 23, 39, 17, 47, -30, 44, 9,
	40, 31, -30, 33, 14, 5,
}
var yyDef = [...]int{

	0, -2, 1, 2, 3, 0, 60, 0, 20, 19,
	14, 15, 6, 7, 0, 0, 61, 0, 0, 0,
	0, 21, 101, 0, 0, 40, 45, 49, 49, 0,
	38, 0, 31, 50, 31, 0, 0, 46, 0, 38,
	58, 47, 32, 0, 23, 0, 25, 0, 0, 30,
	0, 0, 48, 0, 41, 0, 0, 0, 39, 0,
	102, 0, 33, 55, 24, 26, 27, 28, 8, 0,
	0, 4, 5, 29, 0, 0, 0, 68, 53, 70,
	87, 0, 89, 90, 91, -2, -2, 0, 0, 0,
	11, 0, 0, 0, 42, 59, 43, 56, 57, 9,
	10, 81, 0, 51, 0, 0, 85, 55, 0, 0,
	0, 0, 98, 0, 12, 13, 0, 0, 0, 22,
	44, 83, 82, 0, 16, 0, 69, 103, 0, 71,
	54, 94, 95, 96, 0, 99, 97, 0, 62, 0,
	79, 0, 0, 18, 52, 86, 88, 0, 34, 35,
	0, 0, 37, 84, 17, 100, 0, 36, 80, 0,
	63, 64, 65, 66, 67, 0, 0, 77, 0, 74,
	75, 0, 78, 72, 73, 76,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	59, 60, 3, 57, 58, 56,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:130
		{
			yyVAL.literal = yyDollar[1].identifier
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:133
		{
			yyVAL.literal = yyDollar[1].identifier
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:138
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:141
		{
			yyVAL.identifier = yyDollar[1].identifier
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:146
		{
			yyVAL.signedNumber = yyDollar[1].signedNumber
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:149
		{
			yyVAL.signedNumber = -yyDollar[2].signedNumber
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:152
		{
			yyVAL.signedNumber = yyDollar[2].signedNumber
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:157
		{
			yyVAL.float = yyDollar[1].float
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:160
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:163
		{
			yyVAL.float = yyDollar[2].float
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:168
		{
			yyVAL.columnName = yyDollar[1].identifier
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:171
		{
			yyVAL.columnName = "ROWID"
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:176
		{
			yyVAL.columnNameList = []string{yyDollar[1].columnName}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:179
		{
			yyVAL.columnNameList = append(yyDollar[1].columnNameList, yyDollar[3].columnName)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:184
		{
			yyVAL.columnNameList = yyDollar[2].columnNameList
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:189
		{
			yyVAL.columnName = yyDollar[1].columnName
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:194
		{
			yyVAL.columnNameList = []string{yyDollar[1].columnName}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:197
		{
			yyVAL.columnNameList = append(yyDollar[1].columnNameList, yyDollar[3].columnName)
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:203
		{
			yyVAL.columnConstraint = ccPrimaryKey{yyDollar[3].sortOrder, yyDollar[4].bool}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:206
		{
			yyVAL.columnConstraint = ccNull(true)
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:209
		{
			yyVAL.columnConstraint = ccNull(false)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:212
		{
			yyVAL.columnConstraint = ccUnique(true)
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:215
		{
			yyVAL.columnConstraint = ccDefault(yyDollar[2].signedNumber)
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:218
		{
			yyVAL.columnConstraint = ccDefault(yyDollar[2].literal)
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:221
		{
			yyVAL.columnConstraint = ccDefault(nil)
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:224
		{
			yyVAL.columnConstraint = ccCollate(yyDollar[2].identifier)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:227
		{
			yyVAL.columnConstraint = ccReferences(yyDollar[1].foreignKeyClause)
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:232
		{
			yyVAL.columnConstraintList = nil
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:235
		{
			yyVAL.columnConstraintList = []columnConstraint{yyDollar[1].columnConstraint}
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:238
		{
			yyVAL.columnConstraintList = append(yyDollar[1].columnConstraintList, yyDollar[2].columnConstraint)
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:243
		{
			yyVAL.tableConstraint = TablePrimaryKey{yyDollar[4].indexedColumnList}
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:246
		{
			yyVAL.tableConstraint = TableUnique{
				IndexedColumns: yyDollar[3].indexedColumnList,
			}
		}
	case 36:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:251
		{
			yyVAL.tableConstraint = TableForeignKey{
				Columns: yyDollar[4].columnNameList,
				Clause:  yyDollar[6].foreignKeyClause,
			}
		}
	case 37:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:259
		{
			yyVAL.foreignKeyClause = ForeignKeyClause{
				ForeignTable:      yyDollar[2].identifier,
				ForeignColumns:    yyDollar[3].columnNameList,
				Deferrable:        yyDollar[4].bool,
				InitiallyDeferred: yyDollar[5].bool,
				Triggers:          yyDollar[6].triggerList,
			}
		}
	case 38:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:270
		{
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:271
		{
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:275
		{
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:276
		{
			yyVAL.tableConstraintList = []TableConstraint{yyDollar[3].tableConstraint}
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:279
		{
			yyVAL.tableConstraintList = append(yyDollar[1].tableConstraintList, yyDollar[4].tableConstraint)
		}
	case 43:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:285
		{
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:286
		{
			yyVAL.bool = true
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:291
		{
			yyVAL.columnDefList = []ColumnDef{yyDollar[1].columnDef}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:294
		{
			yyVAL.columnDefList = append(yyDollar[1].columnDefList, yyDollar[3].columnDef)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:299
		{
			yyVAL.columnDef = makeColumnDef(yyDollar[1].columnName, yyDollar[2].name, yyDollar[3].columnConstraintList)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:302
		{
			yyVAL.columnDef = makeColumnDef("REPLACE", yyDollar[2].name, yyDollar[3].columnConstraintList)
		}
	case 49:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:307
		{
			yyVAL.name = ""
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:310
		{
			yyVAL.name = yyDollar[1].identifier
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:313
		{
			yyVAL.name = yyDollar[1].identifier
		}
	case 52:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:316
		{
			yyVAL.name = yyDollar[1].identifier
		}
	case 53:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:321
		{
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:322
		{
			yyVAL.collate = yyDollar[2].literal
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:327
		{
			yyVAL.sortOrder = Asc
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:330
		{
			yyVAL.sortOrder = Asc
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:333
		{
			yyVAL.sortOrder = Desc
		}
	case 58:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:338
		{
			yyVAL.withoutRowid = false
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:341
		{
			yyVAL.withoutRowid = true
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:346
		{
			yyVAL.unique = false
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:349
		{
			yyVAL.unique = true
		}
	case 62:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:354
		{
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:355
		{
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:357
		{
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:359
		{
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:361
		{
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:363
		{
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:367
		{
			yyVAL.indexedColumnList = []IndexedColumn{yyDollar[1].indexedColumn}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:370
		{
			yyVAL.indexedColumnList = append(yyDollar[1].indexedColumnList, yyDollar[3].indexedColumn)
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:375
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:380
		{
			yyVAL.indexedColumn = newIndexColumn(yyDollar[1].expr, yyDollar[2].collate, yyDollar[3].sortOrder)
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:385
		{
			yyVAL.triggerAction = ActionSetNull
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:388
		{
			yyVAL.triggerAction = ActionSetDefault
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:391
		{
			yyVAL.triggerAction = ActionCascade
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:394
		{
			yyVAL.triggerAction = ActionRestrict
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:397
		{
			yyVAL.triggerAction = ActionNoAction
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:402
		{
			yyVAL.trigger = TriggerOnDelete(yyDollar[3].triggerAction)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:405
		{
			yyVAL.trigger = TriggerOnUpdate(yyDollar[3].triggerAction)
		}
	case 79:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:410
		{
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:411
		{
			yyVAL.triggerList = append(yyDollar[1].triggerList, yyDollar[2].trigger)
		}
	case 81:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:416
		{
			yyVAL.bool = false
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:419
		{
			yyVAL.bool = true
		}
	case 83:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:424
		{
			yyVAL.bool = false
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:427
		{
			yyVAL.bool = true
		}
	case 85:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:432
		{
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:433
		{
			yyVAL.where = yyDollar[2].expr
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:438
		{
			yyVAL.expr = nil
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:441
		{
			yyVAL.expr = ExFunction{yyDollar[1].identifier, yyDollar[3].exprList}
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:444
		{
			yyVAL.expr = yyDollar[1].signedNumber
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:447
		{
			yyVAL.expr = yyDollar[1].float
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:450
		{
			yyVAL.expr = yyDollar[1].identifier
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:453
		{
			yyVAL.expr = ExColumn(yyDollar[1].identifier)
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:456
		{
			yyVAL.expr = ExColumn(yyDollar[1].identifier)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:459
		{
			yyVAL.expr = ExBinaryOp{yyDollar[2].identifier, yyDollar[1].expr, yyDollar[3].expr}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:462
		{
			yyVAL.expr = ExBinaryOp{"+", yyDollar[1].expr, yyDollar[3].expr}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:465
		{
			yyVAL.expr = ExBinaryOp{"-", yyDollar[1].expr, yyDollar[3].expr}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:468
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 98:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:473
		{
			yyVAL.exprList = nil
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:476
		{
			yyVAL.exprList = []Expression{yyDollar[1].expr}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:479
		{
			yyVAL.exprList = append(yyDollar[1].exprList, yyDollar[3].expr)
		}
	case 101:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:484
		{
			yylex.(*lexer).result = SelectStmt{Columns: yyDollar[2].columnNameList, Table: yyDollar[4].identifier}
		}
	case 102:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:489
		{
			yylex.(*lexer).result = CreateTableStmt{
				Table:        yyDollar[3].identifier,
				Columns:      yyDollar[5].columnDefList,
				Constraints:  yyDollar[6].tableConstraintList,
				WithoutRowid: yyDollar[8].withoutRowid,
			}
		}
	case 103:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.go.y:499
		{
			yylex.(*lexer).result = CreateIndexStmt{
				Index:          yyDollar[4].identifier,
				Table:          yyDollar[6].identifier,
				Unique:         yyDollar[2].unique,
				IndexedColumns: yyDollar[8].indexedColumnList,
				Where:          yyDollar[10].where,
			}
		}
	}
	goto yystack /* stack new state and value */
}
